 
 
// //  const primeiroValor = 10
// //  const segundoValor = 15

// //  const resultado = primeiroValor * segundoValor

// //  console.log(resultado)


// const idade = 55

// const maiorDeIdade = idade >= 18
// const ateCinquentaAnos = idade <= 50

//                // false // true 

// console.log (maiorDeIdade && ateCinquentaAnos)

// //#exercicio &&

// const a = true
// const b = false
// const c = true 

// console.log("a &&b:", a && b)

// console.log("a && c:", b && c)

// console.log("a && c:", a && c)

// console.log(a && b && c)

// const idade = 31

// const maiorQue18 = idade !== 31
// const menorQue30 = idade < 30

// console.log(maiorQue18 || menorQue30)

//exer ||


// const a = true
// const b = false
// const c = true 

// console.log(!a

const nome = "Carol"
const idade = 31
const maiorDeIdade = idade >= 18
const idade2050 = (2050 - 2022) + idade

console.log(`a ${nome} tem ${idade} anos, é maior de idade
 (${maiorDeIdade} e em 2050 ela terá ${idade2050} anos em 2050`)






